### ISSUE TITLE
[FEAT] 회원가입 & 로그인 로직 구현 - 화면 넘김 및 입력 파트

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [CPR2U/CPR2U-iOS#12]
## 문제 상황
VC to VC 넘김 및 키보드를 통한 입력 관련 로직 구현

## 반영 형태 및 SEQUENCE

**관련 ViewController**
|Class Name|UI|
|:---:|:---|
|**PhoneNumberVertificationViewController**|1.휴대폰 번호 입력 화면|
|**SMSCodeVertificationViewController**|2. 휴대폰 번호 인증 화면|
|**NicknameVertificationViewController**|3. 닉네임 입력 화면|

|**전체 화면 공통**|
|:---|
|1. NavigationController를 통한 화면 넘김|
|2. 키보드 출현|

|**휴대폰 번호 입력 화면**|
|:---|
|1. SEND 버튼 활성화 & 비활성화 판별문|

|**휴대폰 번호 인증 화면**|
|:---|
|1. CONFIRM 버튼 활성화 & 비활성화 판별문|
|2. 인증번호 입력 View 자동 Highlight 넘김 동작|

|**닉네임 입력 화면**|
|:---|
|1. 닉네임 사용 가능 판별문(중복 검사가 아닌 특수문자 포함 여부 관련)|

## TODO
- [x] Navigation Controller 연결
- [x] 키보드 출현
- [x] 휴대폰 번호 입력 화면 Task
- [x] 휴대폰 번호 인증 화면 Task
- [x] 닉네임 입력 화면 Task
