### ISSUE TITLE
[FEAT] 교육 로직 구현 - 메인 파트

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [CPR2U/CPR2U-iOS#26]
## 문제 상황
교육 탭 메인 화면에서 필요한 로직 구현

## 반영 형태 및 SEQUENCE
1. ViewModel 작성 (아래 항목 포함)
1. ProgressBar 갱신
2. 각 컨텐츠(강의, 퀴즈, 자세 연습) 진입 조건 판별
3. Certificate 취득 조건 판별

## TODO
- [ ] ViewModel 작성 (아래 항목 포함)
- [ ] ProgressBar 갱신
- [ ] 각 컨텐츠(강의, 퀴즈, 자세 연습) 진입 조건 판별
- [ ]  Certificate 취득 조건 판별
