### ISSUE TITLE
[FEAT] 사용자 주소 입력 기능 구현

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [CPR2U/CPR2U-iOS#39]
## 문제 상황
수료증을 얻은 후, 사용자의 거주지를 선택하는 Alert 띄우기 

## 반영 형태 및 SEQUENCE
1. 사용자의 거주지 선택 Alert UI 구현
2. 사용자 거주지 선택 관련 로직 구현
3. 사용자 거주지 선택 관련 네트워크 계층 구현
4. 3번의 결과에 따른 API 연결

## TODO
- [ ] 사용자의 거주지 선택 Alert UI 구현
- [ ] 사용자 거주지 선택 관련 로직 구현
- [ ] 사용자 거주지 선택 관련 네트워크 계층 구현
- [ ] API 연결
