### ISSUE TITLE
[FEAT] 호출 화면 UI 구현

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [CPR2U/CPR2U-iOS#42]
## 문제 상황
호출 화면 UI 구현하기

## 반영 형태 및 SEQUENCE
**메인 화면**
- 상단 주소
- 중앙 Map (Google Maps API)
- 하단 3초 버튼
- 하단 3-2-1 애니메이션

**호출 결과 화면**

## TODO
- [x] 메인 화면 UI
- [x] 메인 화면 3-2-1 애니메이션
- [x] 호출 결과 화면
