### ISSUE TITLE
[FEAT] 회원가입 & 로그인 UI 구현

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [CPR2U/CPR2U-iOS#7]
## 문제 상황
회원가입 및 로그인 화면 UI 구현하기

## 반영 형태 및 SEQUENCE
**회원가입 및 로그인 화면 UI**
1. 휴대폰 번호 인증 화면 UI
2. 닉네임 입력 화면 UI

## TODO
- [x] 휴대폰 번호 입력 화면 UI
- [x] 휴대폰 번호 인증 화면 UI
- [x] 닉네임 입력 화면 UI
- [x] Toast Message UI
