### ISSUE TITLE
[FIX] 전반적인 UI 수정

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [CPR2U/CPR2U-iOS#87]
## 문제 상황
앱의 전반적인 UI를 개선합니다.

## 반영 형태 및 SEQUENCE
- 교육 메인 탭
- 교육 Alert
- 출동 전 Bottom Sheet
- 출동 후 Bottom Sheet
- 출동 Alert (추가)
- 호출 후 화면

## TODO
- [ ] 교육 메인 탭
- [ ] 교육 Alert
- [ ] 출동 전 Bottom Sheet
- [ ] 출동 후 Bottom Sheet
- [ ] 출동 Alert (추가)
- [ ] 호출 후 화면
