### ISSUE TITLE
[FIX] 교육 자세 연습 기준 수정 및 결과 화면 로직 구현

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [CPR2U/CPR2U-iOS#90]
## 문제 상황
교육 탭 자세 연습 시의 일반적인 기준값의 수정과 결과 화면 UI의 로직 연결이 필요

## 반영 형태 및 SEQUENCE
1. 자세 연습 로직 수정
2. 자세 연습 기준값 수정
3. 결과 화면 UI 로직 연결

## TODO
- [x] 자세 연습 로직 수정
- [x] 자세 연습 기준값 수정
- [x] 결과 화면 UI 로직 연결
